#![recursion_limit = "1000"]

extern crate num;
extern crate serde;
#[macro_use]
extern crate serde_derive;
#[macro_use]
extern crate error_chain;

mod rp_path;
mod rp_path_fragment;
mod rp_loc;
mod rp_name;
mod rp_number;
mod rp_package;
mod rp_type;
mod rp_type_id;
mod rp_modifier;
mod rp_modifiers;
mod loc;
mod merge;
pub mod errors;
mod rp_by_type_match;
mod rp_by_value_match;
mod rp_code;
mod rp_decl;
mod rp_enum_body;
mod rp_enum_variant;
mod rp_field;
mod rp_field_init;
mod rp_instance;
mod rp_interface_body;
mod rp_match_condition;
mod rp_match_decl;
mod rp_match_kind;
mod rp_match_member;
mod rp_match_variable;
mod rp_option_decl;
mod rp_registered;
mod rp_service_body;
mod rp_sub_type;
mod rp_tuple_body;
mod rp_type_body;
mod rp_value;

pub use self::loc::*;
pub use self::merge::*;
pub use self::rp_by_type_match::*;
pub use self::rp_by_value_match::*;
pub use self::rp_code::*;
pub use self::rp_decl::*;
pub use self::rp_enum_body::*;
pub use self::rp_enum_body::*;
pub use self::rp_enum_variant::*;
pub use self::rp_field::*;
pub use self::rp_field_init::*;
pub use self::rp_instance::*;
pub use self::rp_interface_body::*;
pub use self::rp_loc::*;
pub use self::rp_match_condition::*;
pub use self::rp_match_decl::*;
pub use self::rp_match_kind::*;
pub use self::rp_match_member::*;
pub use self::rp_match_variable::*;
pub use self::rp_modifier::*;
pub use self::rp_modifiers::*;
pub use self::rp_name::*;
pub use self::rp_number::*;
pub use self::rp_option_decl::*;
pub use self::rp_package::*;
pub use self::rp_path::*;
pub use self::rp_path_fragment::*;
pub use self::rp_registered::*;
pub use self::rp_service_body::*;
pub use self::rp_sub_type::*;
pub use self::rp_tuple_body::*;
pub use self::rp_type::*;
pub use self::rp_type_body::*;
pub use self::rp_type_id::*;
pub use self::rp_value::*;
