use core::RpNumber;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Token {
    Identifier(String),
    TypeIdentifier(String),
    Number(RpNumber),
    LeftCurly,
    RightCurly,
    LeftBracket,
    RightBracket,
    LeftParen,
    RightParen,
    SemiColon,
    Colon,
    Comma,
    Dot,
    Scope,
    Optional,
    Slash,
    Equals,
    HashRocket,
    CodeOpen,
    CodeClose,
    CodeContent(String),
    String(String),
    // identifier-style keywords
    InterfaceKeyword,
    TypeKeyword,
    EnumKeyword,
    TupleKeyword,
    PackageKeyword,
    MatchKeyword,
    UseKeyword,
    AsKeyword,
    AnyKeyword,
    FloatKeyword,
    DoubleKeyword,
    SignedKeyword,
    UnsignedKeyword,
    BooleanKeyword,
    StringKeyword,
    BytesKeyword,
    TrueKeyword,
    FalseKeyword,
}
