[package]
name = "it"
version = "0.1.0"
edition = "2021"
authors = ["John-John Tedro <udoprog@tedro.se>"]

[features]
default = ["migrate-structures"]
migrate-structures = ["fs_extra"]

[dependencies]
relative-path = { version = "1.7.0", features = ["serde"] }
rayon = "1.5.3"
anyhow = "1.0.58"
thiserror = "1.0.31"
walkdir = "2.3.2"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.82"
serde_yaml = "0.8.24"
diff = "0.1.13"
log = "0.4.17"
env_logger = "0.9.0"
handlebars = "4.3.1"
tokio = { version = "1.20.4", features = ["full", "macros"] }
tokio-stream = "0.1.9"
futures = "0.3.21"
rand = "0.8.5"
unicode-width = "0.1.9"
memchr = "2.5.0"
num_cpus = "1.13.1"
humantime-serde = "1.1.1"
ansi-escapes = "0.1.1"

fs_extra = { version = "1.2.0", optional = true }

[target.'cfg(windows)'.dependencies]
dunce = "1.0.2"

[target.'cfg(unix)'.dependencies]
users = "0.11.0"
