[package]
name = "reproto-it"
version = "0.1.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]

[dependencies]
relative-path = "0.3"
rayon = "1.0"
failure = "0.1"
walkdir = "2.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
diff = "0.1"

[[bin]]
name = "it"
path = "main.rs"

[lib]
name = "it"
path = "lib.rs"
