#!/usr/bin/env bash

script="$1"
input_path=input

if [[ ! -d $input_path ]]; then
    exit 0
fi

while read input; do
    project=$(basename $(dirname $script))
    name=$(basename $input)

    out=output-${project#workdir-}/$name.out

    mkdir -p $(dirname $out)

    echo "Running $input against $script into $out"
    cat $input | $script > $out
done < <(find $input_path -type f -name '*.json')
