#!/usr/bin/env bash
# echo all supported project suites depending on what tools are available

noecho() {
    command=$1
    shift
    $command "$@" 1> /dev/null 2>&1
    return $?
}

if noecho mvn --version; then
    echo "java"
else
    echo "disabling: java" 1>&2
fi

if noecho node --version && noecho babel --version; then
    echo "js"
else
    echo "disabling: js" 1>&2
fi

if noecho $PYTHON --version; then
    echo "python"
else
    echo "disabling: python" 1>&2
fi

if noecho cargo --version; then
    echo "rust"
else
    echo "disabling: rust" 1>&2
fi
