#!/bin/bash

green="\033[0;32m"
red="\033[0;31m"
nc="\033[0m"

overall_exit_code=0

while read path; do
    dir=$(dirname $path)
    name=$(basename $dir)

    if ! $MAKE -C "$dir" -f "$ROOT/it/lib.mk" "$@"; then
        overall_exit_code=1
        tput bold
        echo -e "${red}Failed: ${name} ($@)${nc}"
    else
        tput bold
        echo -e "${green}Succeeded: ${name} ($@)${nc}"
    fi
done < <(ls -1 it/test-*/Makefile)

exit $overall_exit_code
