#!/bin/bash

green="\033[0;32m"
red="\033[0;31m"
nc="\033[0m"

overall_exit_code=0

while read test; do
    echo $test

    dir=$(dirname $test)
    test=$(basename $dir)

    make -C $dir "$@"
    exit_code=$?

    if [[ $exit_code -ne 0 ]]; then
        tput bold
        echo -e "${red}Test failed: ${test}${nc}"
        overall_exit_code=1
    else
        make -C $dir clean
        tput bold
        echo -e "${green}Test succeeded: ${test}${nc}"
    fi
done < <(find it -type d -name '__*' -prune -o -name Makefile -maxdepth 2 -print)

exit $overall_exit_code
