#!/bin/bash
# Handles publishing of components in the right order.
# use SKIP environment variable to specify modules to skip

target=$PWD/target
root=$PWD

candidates=()
candidates+=(lib/semver)
candidates+=(lib/core)
candidates+=(lib/path-lexer lib/path-parser)
candidates+=(lib/lexer lib/ast lib/parser)
candidates+=(lib/derive)
candidates+=(lib/manifest lib/repository lib/backend lib/semck)

for manifest in $root/lib/backend-*/Cargo.toml; do
    b=$(basename $(dirname $manifest))
    candidates+=(lib/$b)
done

candidates+=(server cli)

targets=()

for candidate in ${candidates[*]}; do
    if [[ $SKIP != *"$candidate"* ]]; then
        targets+=($candidate)
    fi
done

echo "TARGETS: ${targets[*]}"

export CARGO_TARGET_DIR=$target

for target in ${targets[*]}; do
    cargo publish --manifest-path=$root/$target/Cargo.toml
done
