#!/bin/bash
# Handles publishing of components in the right order.
# use SKIP environment variable to specify modules to skip

target=$PWD/target
root=$PWD

candidates="lib/semver lib/core lib/lexer lib/ast lib/manifest lib/parser lib/repository lib/backend lib/semck"

for manifest in $root/lib/backend-*/Cargo.toml; do
    b=$(basename $(dirname $manifest))
    candidates="$candidates lib/$b"
done

candidates="$candidates server cli"

targets=""

for candidate in $candidates; do
    if [[ $SKIP != *"$candidate"* ]]; then
        targets="$targets $candidate"
    fi
done

echo "TARGETS: $targets"

export CARGO_TARGET_DIR=$target

for target in $targets; do
    cargo publish --manifest-path=$root/$target/Cargo.toml
done

cargo publish --manifest-path=$root/Cargo.toml
