#!/bin/bash
# runs a project against all provided inputs.

set -e

status=0

script=$1
shift

if [[ ! -x $script ]]; then
    echo "$script: not executable"
    exit 1
fi

while [[ $# -gt 0 ]]; do
    input=$1
    output=$2

    if ! $script < $input > $output; then
        status=$?
    fi

    shift 2
done

exit $status
